name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install & build
        run: |
          yarn install
          yarn run build

      - name: Deploy on GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: build
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository-name: zopieux/zopieux.github.io
          branch: master
          target-folder: mugctl
          commit-message: Deploy mugctl.
          git-config-name: Alexandre Macabies
          git-config-email: <web+oss@zopieux.com>
