name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 'v16.11.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install & build
        run: |
          yarn install
          yarn run build

      - name: Deploy on GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          folder: build
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository-name: zopieux/zopieux.github.io
          branch: master
          target-folder: mugctl
          commit-message: Deploy mugctl.
          git-config-user: Alexandre Macabies
          git-config-email: <web+oss@zopieux.com>
